### ISSUE TITLE
Checkout Vertical

### ISSUE THREAD

**Issue by PeopleMakeCulture** [1904gs-terrific-tigers/animals#13]
- Handles cart submit
- Handles GET /api/cart - delivers a full obj with animal data
- Handles PUT /api/cart/ with no payload
- Handles POST /api/cart/:animalId with payload of quantity
- Handles DELETE /api/cart/:animalId with no payload

All routes need a logged in user
Should check for existence of cart in all cases.
Behavior depends on items in cart

**Comment by marvinody** [comment]
update
-  Handles POST /api/cart/:animalId with payload of {quantity: number}. this should add to the cart the amount specified
- Handles PUT /api/cart/:animalId with payload of {quantity: number}. this should set the item to the amount specfied
